import {
  Registry,
  Counter,
  Gauge,
  collectDefaultMetrics,
} from 'prom-client';

/**
 * Prometheus metrics registry and metric definitions for IRSB Watchtower
 */

// Create a new registry
export const registry = new Registry();

// Collect default Node.js metrics (memory, CPU, etc.)
collectDefaultMetrics({ register: registry });

/**
 * Total number of scan ticks executed
 */
export const ticksTotal = new Counter({
  name: 'watchtower_ticks_total',
  help: 'Total number of scan ticks executed',
  labelNames: ['chainId'] as const,
  registers: [registry],
});

/**
 * Total number of alerts generated
 */
export const alertsTotal = new Counter({
  name: 'watchtower_alerts_total',
  help: 'Total number of alerts generated by rules',
  labelNames: ['ruleId', 'severity', 'chainId'] as const,
  registers: [registry],
});

/**
 * Total number of errors encountered
 */
export const errorsTotal = new Counter({
  name: 'watchtower_errors_total',
  help: 'Total number of errors encountered',
  labelNames: ['type', 'chainId'] as const,
  registers: [registry],
});

/**
 * Last processed block number per chain
 */
export const lastBlock = new Gauge({
  name: 'watchtower_last_block',
  help: 'Last processed block number',
  labelNames: ['chainId'] as const,
  registers: [registry],
});

/**
 * Total number of actions executed
 */
export const actionsTotal = new Counter({
  name: 'watchtower_actions_total',
  help: 'Total number of actions executed',
  labelNames: ['actionType', 'status', 'chainId'] as const,
  registers: [registry],
});

/**
 * Current number of active scans in progress
 */
export const activeScans = new Gauge({
  name: 'watchtower_active_scans',
  help: 'Number of scan cycles currently in progress',
  labelNames: ['chainId'] as const,
  registers: [registry],
});

/**
 * Metrics helper functions
 */
export const metrics = {
  /**
   * Record a scan tick
   */
  recordTick(chainId: number): void {
    ticksTotal.inc({ chainId: String(chainId) });
  },

  /**
   * Record an alert/finding
   */
  recordAlert(ruleId: string, severity: string, chainId: number): void {
    alertsTotal.inc({ ruleId, severity, chainId: String(chainId) });
  },

  /**
   * Record an error
   */
  recordError(type: string, chainId?: number): void {
    errorsTotal.inc({ type, chainId: chainId ? String(chainId) : 'unknown' });
  },

  /**
   * Update last processed block
   */
  setLastBlock(chainId: number, blockNumber: bigint): void {
    lastBlock.set({ chainId: String(chainId) }, Number(blockNumber));
  },

  /**
   * Record an action execution
   */
  recordAction(actionType: string, status: 'success' | 'failure' | 'dry_run', chainId: number): void {
    actionsTotal.inc({ actionType, status, chainId: String(chainId) });
  },

  /**
   * Increment active scans
   */
  scanStarted(chainId: number): void {
    activeScans.inc({ chainId: String(chainId) });
  },

  /**
   * Decrement active scans
   */
  scanCompleted(chainId: number): void {
    activeScans.dec({ chainId: String(chainId) });
  },

  /**
   * Get metrics output for Prometheus
   */
  async getMetrics(): Promise<string> {
    return registry.metrics();
  },

  /**
   * Get content type for metrics response
   */
  getContentType(): string {
    return registry.contentType;
  },
};
